[project]
name = "verifiers"
authors = [
    {name = "William Brown", email = "williambrown97@gmail.com"},
]
version = "0.1.0"
description = "Verifiers for reinforcement learning with LLMs"
license = {text = "MIT"}
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch==2.6.0",
    "liger-kernel>=0.5.10",
    "setuptools",
    "deepspeed",
    "accelerate",
    "peft",
    "wandb",
    "rich",
    "trl>=0.17.0",
    "requests>=2.32.3",
    "vllm>=0.8.5.post1",
    "openai>=1.81.0",
    "datasets>=3.6.0",
    "transformers",
]

[project.optional-dependencies]
all = [
    "ipykernel",
    "ipywidgets",
    "duckduckgo-search",
    "brave-search",
    "reasoning-gym",
    "smolagents>=1.15.0",
]

[project.scripts]
vf-vllm = "verifiers.inference.vllm_server:cli_main"

[tool.setuptools]
packages = ["verifiers"]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
