[project]
name = "verifiers"
authors = [
    {name = "William Brown", email = "williambrown97@gmail.com"},
]
version = "0.1.0"
description = "Verifiers for reinforcement learning with LLMs"
license = {text = "MIT"}
requires-python = ">=3.11,<3.13"
dependencies = [
    "torch>=2.6.0",
    "setuptools",
    "deepspeed",
    "accelerate",
    "peft",
    "wandb",
    "rich",
    "trl>=0.17.0",
    "liger-kernel",
    "requests>=2.32.3",
    "vllm>=0.8.5.post1",
    "openai>=1.81.0",
    "datasets>=3.6.0",
    "transformers>=4.52.2",
]

[project.optional-dependencies]
jupyter = [
    "ipykernel",
    "ipywidgets"
]
tools = [
    "duckduckgo-search",
    "brave-search",
    "smolagents>=1.15.0",
]
extras = [
    "reasoning-gym"
]

[tool.setuptools]
packages = ["verifiers"]
