[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "truthful_qa"
version = "0.1.0"
description = "TruthfulQA environment for evaluating model truthfulness and informativeness"
dependencies = [
    "verifiers",
    "datasets",
    "openai",
]