[project]
name = "math-group"
version = "0.1.0"
dependencies = [
    "verifiers>=0.1.4",
    "math-verify>=0.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["math_group.py"]
