[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "toxicity_explanation"
version = "0.1.0"
description = "Toxicity detection with context-aware explanations using JudgeRubric"
dependencies = [
    "verifiers",
    "datasets",
    "openai",
]