[project]
name = "continuation-quality"
version = "0.1.1"
dependencies = [
    "verifiers>=0.1.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["continuation_quality.py"]
