[project]
name = "vf-aime2025"
description = "AIME-25 evaluation environment"
tags = ["math", "eval", "single-turn"]
version = "0.1.7"
requires-python = ">=3.11,<3.13"
dependencies = [
    "verifiers>=0.1.2.post0",
    "math-verify>=0.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["vf_aime2025.py"]
